import os
from .util import write_file_safe, is_tool

def generate_dockerfile(logger, dry_run=False):
    """
    Generates a Dockerfile.
    """
    # Detect python version (read from pyproject or default)
    base_image = "python:3.10-slim"
    
    # Detect requirements or toml
    install_cmd = "pip install --no-cache-dir ."
    copy_files = "COPY . ."
    
    if os.path.exists("requirements.txt"):
        install_cmd = "pip install --no-cache-dir -r requirements.txt"
    
    # Check for poetry/uv?
    # Simplified logic for now
    
    content = f"""# Generated by pyclit
FROM {base_image} as builder

WORKDIR /app

# Install dependencies first for caching
COPY requirements.txt* pyproject.toml* ./
RUN {install_cmd}

COPY . .

# Detect Entrypoint if possible
# CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
"""
    write_file_safe("Dockerfile", content, logger, dry_run)
